version: '3'

services:
  sampleproject:
    image: drill4j/todomvc:${SAMPLE_APP_VERSION}
    environment:
      JS_AGENT_HOST: ${JS_AGENT_HOST}
      JS_AST_PARSER_VERSION: ${JS_AST_PARSER_VERSION}
      BUILD_VERSION: ${SAMPLE_APP_VERSION}
    ports:
      - "${SAMPLE_APP_PORT}:80"
